### ISSUE TITLE
Error running fold_feat_gen.py (2nd)

### ISSUE THREAD

**Issue by kimdn** [IBM/fold2seq#8]
I'm not sure whether
https://github.com/IBM/fold2seq/issues/1
is fixed.

With example data
```
WE46901:run_example kimd999$ cat domain_list.txt
/Users/kimd999/research/projects/Margaret/code/fold2seq/data/example/1aj4A00-2-161   1aj4  A  2   161
/Users/kimd999/research/projects/Margaret/code/fold2seq/data/example/1bzqK00-801-924 1bzq  K  801 924
/Users/kimd999/research/projects/Margaret/code/fold2seq/data/example/1ge0A00-1-130   1ge0  A  1   130
```

I see
```

total number of seqs: 470679
removed # seqs in ss.txt: 9337
Traceback (most recent call last):
  File "/Users/kimd999/research/projects/Margaret/code/fold2seq/data/fold_feat_gen.py", line 152, in <module>
    x1,x2 = selection(line[0] ,  line[2], int(line[3]), int(line[4]), seq_ss)
  File "/Users/kimd999/research/projects/Margaret/code/fold2seq/data/fold_feat_gen.py", line 42, in selection
    start = start.replace(')','')
AttributeError: 'int' object has no attribute 'replace'
```

**Comment by kimdn** [comment]
Even after I commented out these replace lines, still I see

```
(fold2seq) [kimd999@tlogin3 data]$ ./run_this.sh
total number of seqs: 470679
removed # seqs in ss.txt: 9337
Traceback (most recent call last):
  File "fold_feat_gen.py", line 152, in <module>
    x1,x2 = selection(line[0] ,  line[2], int(line[3]), int(line[4]), seq_ss)
  File "fold_feat_gen.py", line 79, in selection
    raise ValueError("encounter inconsistent pdb structure:"+pdb_path+chain+" "+str(start)+','+str(end))
ValueError: encounter inconsistent pdb structure:example/1aj4A00-2-161A 2,161

```
both at my mac and linux
